# Generated by Django 2.1.5 on 2019-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190217_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='github_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='medium_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
